### PR TITLE
Fix/TR-1240/Restore the previous version of text reader aside the new one

### PR DESCRIPTION
**Pull request by jsconan**
Related to: https://oat-sa.atlassian.net/browse/TR-1240

Restore the previous version of the textReader interaction aside the new version.
The purpose is to allow existing items to continue working without having to fix them all one by one.

> **Note:** the code for the PCI has been restored from its previous state before it was deleted. So no need to review it in details. This is a legacy code, but we don't need to update/fix it, it was done already by the refactoring to the IMS standard.

How to test (sorry for the monkey job):

- **Update**
    1. install a TAO instance with the pciSamples extension from `v3.0.1`.
    2. import the test `test_textReader_v0.9.0.zip` from the ticket
    3. publish the test, and check it can be passed well
    4. check the preview of the item is ok
    5. checkout the tag `v3.1.0`
    6. update TAO
    7. check the test cannot be completed
    8. check the test cannot be exported
    9. checkout the branch of this PR
    10. update TAO: the update should go well.
    11. import the test `test_textReader_v1.0.0.zip` from the ticket
    12. publish the test, and check it can be passed well
    13. check the test of the PCI in v0.9.0 can be passed well
    14. check the URL to get the PCI is different for both (in the network panel, check the URL to get the textReader runtime)
    15. check the tests can be exported

- **Install**
    1. install a TAO instance with the branch checked out on pciSamples: the install should go well
    2. import the test `test_textReader_v0.9.0.zip` from the ticket
    3. import the test `test_textReader_v1.0.0.zip` from the ticket
    4. publish the tests, and check they can be passed well
    5. check the URL to get the PCI is different for both (in the network panel, check the URL to get the textReader runtime)
    6. check the preview of the items are ok
    7. check the tests can be exported

**Note:** to check the code is present in both version, you can check the content of the `data` folder:
- manifest for the IMS version: `data/qtiItemImsPci`
- manifest for the OAT version: `data/qtiItemPci`
- registered code (each will have 2 folders): `data/portableElementStorage`

### CODE REVIEW

**Comment by marpesia** [comment]
I have got a popup warning only on Test preview with these steps:

1. install a TAO instance with the pciSamples extension from v3.0.1.
2. import the test test_textReader_v0.9.0.zip from the ticket
3. publish the test, and check it can be passed well
4. check the preview of the item is ok

image

**Review by marpesia — COMMENTED** [review]
I have got a popup warning only on Test preview with the pciSamples extension in all versions.

I've followed all the steps, 'Update' steps, and I have all the time the same results, everything goes well with both tests and with the 3 versions of the repo.

**Comment by jsconan** [comment]
@marpesia The message you got is not related to this feature nor is added by this PR. Actually, it is expected as the config requires each item to be answered in the preview. You'll have it for any test. The issue here is the textReader does not issue a response since this is an informational content. It needs to be aside another interaction in this context.
The preview mentioned in the description of this ticket is the item preview, not the test preview.

**Review by marpesia — APPROVED** [review]
Both test goes well

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ]  Commits messages are meaningful
- [ ]  Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by meefox — APPROVED** [review]
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Pull request merged**
