### PR TITLE
fixed reader bug

### PR DESCRIPTION
**Pull request by no-chris**
bugfix in depp
- create a textReader interaction
- add an image in the first tab
- exit the reader authoring mode : the reader switch to a "preview" mode
- without this fix, the reader doesn't display the picture in preview mode, althoug everything works fine otherwise (in item preview or in authoring mode)
- after applying the fix, the image should display in all modes

### CODE REVIEW

**Comment by no-chris** [comment]
closing because the bug still happens in delivery

**Comment by no-chris** [comment]
fixed with last version of qtiItem extension

**Comment by krampstudio** [comment]
@no-chris is there a direct dependency to taoQtiItem ? because right now
 it requires qtiItemPci that requires taoQtiItem

**Comment by no-chris** [comment]
My problem was that no image was displayed in the reader during the delivery. I thought it was related to this bug but in fact not all, its just that the compile process wouldn't copy all the images found in custom interactions. See https://github.com/oat-sa/extension-tao-itemqti/commit/42df8d25de3e94845d2614ea32659812dc9e692c

So updating qti-item to last version allows for correct generation of deliveries

**Pull request merged**
