### PR TITLE
Feature/tao 3145 ck highlight plugin

### PR DESCRIPTION
**Pull request by krampstudio**
Enables the highlight plugin into the textReader interaction.

Requires https://github.com/oat-sa/tao-core/pull/1001 and https://github.com/oat-sa/extension-tao-itemqti/pull/810

### CODE REVIEW

**Comment by ssipasseuth** [comment]
After updating a pci (either the runtime or creator), you need to register it again in the updater so the new version is registered as the latest one to be used. I have started some documentation here http://forge.taotesting.com/projects/tao/wiki/PCI_development or you can follow the example in this similar PR https://github.com/oat-sa/extension-pcisample/pull/12/files

**Comment by ssipasseuth** [comment]
The underline style and the new highlight styles are identical. Is it expected ?
I can see also a discrepancy from the AC "EM font color = black"

**Comment by krampstudio** [comment]
@dietertaotesting took care of the rendered style. In TAO, we have fg=white bg=orange and in invalsi with have fg=black and bg=orange.

Those changes have been merged into develop yesterday.

**Comment by dietertaotesting** [comment]
White contrasts well with orange, black not so much. Invalsi insists on black though - hence the difference

**Pull request merged**
